<div class="contain">
    <h4>Ma corbeille</h4>
    
    <div class="clearfix">&nbsp;</div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-responsive table-striped">
                <tr class="table-striped">
                    <td> </td>
                    <td> </td>
                    <td><b>N&deg;</b></td>
                    <td><b>Nom fichier</b></td>
                    <td align="center"><b>details</b></td>
                    <td align="center"><b>T&eacute;l&eacute;charger</b></td>
                    <td align="center"><b>supprimer</b></td>
                </tr>
                <tr class="table-striped">
                    <td><input type="checkbox"></td>
                    <td><img src="../public/img/fich.jpg" width="25" height="25"></td>
                    <td><b>1</b></td>
                    <td>mon cv</td>
                    <td align="center">50 ko</td>
                    <td align="center"><a href="#"><span class="glyphicon glyphicon-cloud-download text-primary"></span></a></td>
                    <td align="center"><span class="glyphicon glyphicon-remove text-danger"></span></td>
                </tr>
                <tr class="table-striped">
                    <td><input type="checkbox"></td>
                    <td><img src="../public/img/fich.jpg" width="25" height="25"></td>
                    <td><b>2</b></td>
                    <td>mon parcour universitaire</td>
                    <td align="center">15 Mo</td>
                    <td align="center"><a href="#"><span class="glyphicon glyphicon-cloud-download text-primary"></span></a></td>
                    <td align="center"><span class="glyphicon glyphicon-remove text-danger"></span></td>
                </tr>
                <tr class="table-striped">
                    <td><input type="checkbox"></td>
                    <td><img src="../public/img/fich.jpg" width="25" height="25"></td>
                    <td><b>3</b></td>
                    <td>dossier soneb</td>
                    <td align="center">110 ko</td>
                    <td align="center"><a href="#"><span class="glyphicon glyphicon-cloud-download text-primary"></span></a></td>
                    <td align="center"><span class="glyphicon glyphicon-remove text-danger"></span></td>
                </tr>
            </table>
        </div>
    </div>
</div>
