<div class="contain">
    <h4>Mes couriels envoy&eacute;s</h4>
    <div class="clearfix">&nbsp;</div>
    <div class="clearfix">&nbsp;</div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-responsive table-striped">
                <tr class="table-striped">
                    <td> </td>
                    <td><b>Objet</b></td>
                    <td align="center"><b>De</b></td>
                    <td align="center"><b>Date</b></td>
                    <td align="center"><b>Taille</b></td>
                    <td align="center"><b>supprimer</b></td>
                </tr>
                <tr class="table-striped">
                    <td>&nbsp;</td>
                    <td>mon cv zetgzegzege</td>
                    <td align="center">mon cv</td>
                    <td align="center">2017-02-04</td>
                    <td align="center">10 ko</td>
                    <td align="center"><span class="glyphicon glyphicon-trash text-danger"></span></td>
                </tr>
                <tr class="table-striped">
                    <td>&nbsp;</td>
                    <td>mon parcour universitaire</td>
                    <td align="center">monique</td>
                    <td align="center">2017-02-04</td>
                    <td align="center">110 ko</td>
                    <td align="center"><span class="glyphicon glyphicon-trash text-danger"></span></td>
                </tr>
                <tr class="table-striped">
                    <td>&nbsp;</td>
                    <td>dossier soneb</td>
                    <td align="center">soneb</td>
                    <td align="center">2017-02-04</td>
                    <td align="center">110 ko</td>
                    <td align="center"><span class="glyphicon glyphicon-trash text-danger"></span></td>
                </tr>
            </table>
        </div>
    </div>
</div>
