<div class="contain">
    <h3>Nouveau message</h3>
    <div class="clearfix">&nbsp;</div>
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <span class="col-md-2">De</span>
                <span class="col-md-4">
                    <select name="mmail" class="form-control">
                        <option>bouraimajoezer@gmail.com</option>
                    </select>
                </span>
            </div>
            <div class="clearfix">&nbsp;</div>
            <div class="row">
                <span class="col-md-2">&Agrave;</span>
                <span class="col-md-10">
                    <input type="text" class="form-control">
                </span>
            </div>
            <div class="clearfix">&nbsp;</div>
            <div class="row">
                <span class="col-md-2">Objet;</span>
                <span class="col-md-10">
                    <input type="text" class="form-control">
                </span>
            </div>
            <div class="clearfix">&nbsp;</div>
            <div class="row">
                <span class="col-md-2">&nbsp;</span>
                <span class="col-md-10">
                    <input type="file">
                </span>
            </div>
            <div class="clearfix">&nbsp;</div>
            <div class="row">
                <span class="col-md-2">&nbsp;</span>
                <span class="col-md-10">
                    <textarea rows="10" class="form-control ckeditor"></textarea>
                </span>
                <span class="clearfix">&nbsp;</span>
                <span class="col-md-2">
                     &nbsp;
                </span>
                <span class="col-md-10">
                    <button type="submit"  name="submit" class="btn btn-default"><i class="fa fa-send "></i> &nbsp; Envoyer</button>
                </span>
            </div>
        </div>
    </div>
</div>
