<?php
if (!isset($fichiers)) {
    $fichiers = [];
}

?>
<div class="contain">
    <h4 class="text-warning">Mes fichiers</h4>
    <div class="clearfix">&nbsp;</div>
    <form method="post" action="newFile" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-12">
                <span  data-toggle="collapse" data-target="#demo1" style="cursor: alias;"><a href="#"><i class="fa fa-plus"></i> Ajouter un/des fichier(s)</a></span>

            </div>
            <div id="demo1" class="collapse col-md-12">
                <span class="clearfix">&nbsp;</span>
                <div class="col-md-12">
                    <table class="table table-responsive">
                        <tr>
                            <td colspan="4">
                                <span class="col-md-6"><input type="text" name="descfile[]" class="form-control" placeholder="description fichier" required=""></span>
                                <span class="col-md-4"><input type="file" name="fichier[]"></span>
                                <span class="col-md-2" id="bloc-button">
                                    <button type="button" class="btn btn-success btn-xs"  id="addDoc" >
                                        <i class="fa fa-plus"></i> &nbsp;Nouveau
                                    </button>
                                </span><br>

                            </td>
                        </tr>                               
                    </table> 
                    <table class="table table-responsive"id="tableau_doc" >
                        <tr>
                            <td colspan="4">
                            </td>
                        </tr>
                    </table>

                </div>
                <div class="row">
                    <span class="col-md-10">
                        &nbsp;
                    </span>
                    <span class="col-md-2">
                        <button class="btn btn-primary fa fa-check " type="submit" >&nbsp;Enregistrer</button>
                    </span>
                </div>
            </div>
        </div>
    </form>
    <div class="clearfix">&nbsp;</div>
    <div class="col-md-12 row notification">
        <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div><p><?php $this->flashSession->output() ?></p></div>
        <?php endif; ?>
    </div>
    <div class="clearfix">&nbsp;</div>
    <div class="row">
        <form name="form1">
        <div class="col-md-12">
            <table  class="table table-striped table-responsive table-bordered table-hover ui-datatable" 
                    data-global-search="false"
                    data-length-change="true"
                    data-info="true"
                    data-paging="true"
                    data-page-length="10"
                    >
                <thead class="table-responsive">
                    <tr>
                        <th><input type="checkbox" name="Choix_global" onclick="checTt('form1', 'Choix', true);"/> </th>
                        <th><b>N&deg;</b></th>
                        <th data-filterable="text" data-sortable="true"><b>Nom fichier</b></th>
                        <th><b>details</b></th>
                        <th><b>Taille</b></th>
                        <th align="center"><b>Ouvrir</b></th>
                        <?php if($this->session->get('mod')=="1"): ?><th align="center"><b>Modifier</b></th><?php endif; ?>
                        <?php if($this->session->get('sup')=="1"): ?><th align="center"><b>supprimer</b></th><?php endif; ?>
                                    <!--<th data-filterable="text" data-sortable="true">Date derni&egrave;re commande</th>-->
                                    <!--<th data-filterable="text" data-sortable="true">Total des commandes</th>-->
                    </tr>
                </thead>
                <tbody class="table-responsive">
                    <?php
                    $i = 0;
                    foreach ($fichiers as $file) : $i++;

                        ?>
                        <tr>
                            <td><input type="checkbox" name="Choix_1" onclick="checTt('form1', 'Choix');" size="2"/></td>
                            <td class="text-left valign-middle"><b><?= $i ?> <i class=" fa fa-file-text text-warning"></i></td>
                            <td class="text-center valign-middle"><?= $file->description ?></td>
                            <td class="text-center valign-middle"><?= $file->extension ?></td>
                            <td class="text-center valign-middle"><?= $file->taille ?> ko</td>
                            <td align="center"><a href="<?= $this->url->getBaseUri()."public/archives/".$file->nomfile ?> " target="_blank"><span class="glyphicon glyphicon-eye-open text-primary"></span></a></td>
                            <?php if($this->session->get('mod')=="1"): ?><td align="center"><a href="updateFile?id=<?= $file->idfile ?>"><span class="glyphicon glyphicon-pencil text-warning"></span></a></td><?php endif; ?>
                            <?php if($this->session->get('sup')=="1"): ?><td align="center"><a href="deleteFile?id=<?= $file->idfile ?>" data-confirm="<?= $file->description ?>"><span class="glyphicon glyphicon-trash text-danger"></span></a></td><?php endif; ?>
                        </tr>


                    <?php endforeach;

                    ?>
                </tbody>

              
            </table>
        </div>
        </form>
    </div>
</div>
