<?php 
if(!isset($dossiers)){
    $dossiers=[];
}
?>
<div class="contain">
    <h4 class="text-info">Mes Dossiers</h4>
    <div class="clearfix">&nbsp;</div>
    <div class="row">
        <div class="col-md-12">
           <table class="table table-responsive table-striped">
                <tr class="table-striped">
                    <td> </td>
                    <td><b>N&deg;</b></td>
                    <td><b>Nom dossier</b></td>
                    <td><b>file(s)</b></td>
                    <td align='center'><b>ouvrir</b></td>
                    <td align='center'><b>supprimer</b></td>
                </tr>
                <?php $i=0; foreach ($dossiers as $doc): $i++ ?>
                <tr class="table-striped">
                    <td><img src="../public/img/folder.jpg" width="20" height="20"></td>
                    <td><b><?= $i ?></b></td>
                    <td><?= $doc->nomdos ?></td>
                    <td><?= "(".count($doc->fichier).")" ?></td>
                    <td align="center"><a href="#"><span class="glyphicon glyphicon-eye-open text-primary"></span></a></td>
                    <td align="center"><span class="glyphicon glyphicon-trash text-danger"></span></td>
                </tr>
                <?php endforeach; ?>
               
            </table>
        </div>
    </div>
</div>

