<div class="contain">
    <h3>Mes Dossiers</h3>
    
    <div class="row">
        <div class="col-md-12">
           <table class="table table-responsive table-striped">
                <tr class="table-striped">
                    <td> </td>
                    <td><b>N&deg;</b></td>
                    <td><b>Nom dossier</b></td>
                    <td><b>file(s)</b></td>
                    <td align='center'><b>ouvrir</b></td>
                    <td align='center'><b>supprimer</b></td>
                </tr>
                <tr class="table-striped">
                    <td><img src="../public/img/folder.jpg" width="20" height="20"></td>
                    <td><b>1</b></td>
                    <td>mon cv</td>
                    <td>(05)</td>
                    <td align="center"><a href="#"><span class="glyphicon glyphicon-eye-open text-primary"></span></a></td>
                    <td align="center"><span class="glyphicon glyphicon-trash text-danger"></span></td>
                </tr>
                <tr class="table-striped">
                    <td><img src="../public/img/folder.jpg" width="20" height="20"></td>
                    <td><b>2</b></td>
                    <td>mon parcour universitaire</td>
                    <td>(08)</td>
                    <td align="center"><a href="#"><span class="glyphicon glyphicon-eye-open text-primary"></span></a></td>
                    <td align="center"><span class="glyphicon glyphicon-trash text-danger"></span></td>
                </tr>
                <tr class="table-striped">
                    <td><img src="../public/img/folder.jpg" width="20" height="20"></td>
                    <td><b>3</b></td>
                    <td>dossier soneb</td>
                    <td>(15)</td>
                    <td align="center"><a href="#"><span class="glyphicon glyphicon-eye-open text-primary"></span></a></td>
                    <td align="center"><span class="glyphicon glyphicon-trash text-danger"></span></td>
                </tr>
            </table>
        </div>
    </div>
</div>

