<?php
if (!isset($dossiers)) {
    $dossiers = [];
}

?>
<div class="contain">
    <h4 class="text-warning">Nouveau dossier</h4>

    <form method="post" id="form-folder" action="newFolder" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-3">
                 <div class="clearfix">&nbsp;</div>
                <span><i class="fa fa-folder-open-o fa-5x text-warning"></i></span><br>
                <input type="text" class="form-control fln" placeholder="Nom du dossier" name="foldername" required=""><br>
                 <div class="clearfix">&nbsp;</div>
                <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check btn-primary"></i> Enregistrer </button>
                <span>&nbsp;</span>
                <button type="reset" class="btn btn-default btn-sm">Annuler </button>
            </div>

            <div style="float: left; border: 1px solid #ccc; height: 250px;"></div>

            <div class="col-md-8">
                <table class="table table-responsive">
                    <tr>
                        <td colspan="4">
                            <span class="col-md-6"><input type="text" name="descfile[]" class="form-control" placeholder="description fichier" required=""></span>
                            <span class="col-md-4"><input type="file" name="fichier[]"></span>
                            <span class="col-md-2" id="bloc-button">
                                <button type="button" class="btn btn-success btn-xs"  id="addDoc" >
                                    <i class="fa fa-plus"></i> &nbsp;Nouveau
                                </button>
                            </span><br>

                        </td>
                    </tr>                               
                </table> 
                <table class="table table-responsive"id="tableau_doc" >
                    <tr>
                        <td colspan="4">
                        </td>
                    </tr>
                </table>

            </div>        
        </div>
    </form>
    <div class="clearfix">&nbsp;</div>

    <div class="col-md-12 row notification">
        <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div><p><?php $this->flashSession->output() ?></p></div>
        <?php endif; ?>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-responsive table-striped">
                <tr class="table-striped">
                    <td> </td>
                    <td><b>N&deg;</b></td>
                    <td><b>Nom dossier</b></td>
                    <td><b>file(s)</b></td>
                    <td align='center'><b>ouvrir</b></td>
                    <?php if($this->session->get('sup')=="1"): ?><td align='center'><b>supprimer</b></td><?php endif; ?>
                </tr>
                <?php $i = 0;
                foreach ($dossiers as $doc): $i++; ?>
                    <tr class="table-striped">
                        <td><i class="fa fa-folder-open text-warning"></i></td>
                        <td><b><?= $i ?></b></td>
                        <td><?= $doc->nomdos ?></td>
                        <td><?= "(" . count($doc->fichier) . ")" ?></td>
                        <td align="center"><a href="openFolder?id=<?= $doc->iddos ?>"><span class="glyphicon glyphicon-eye-open text-primary"></span></a></td>
                        <?php if($this->session->get('sup')=="1"): ?><td align="center"><a href="deleteFolder?id=<?= $doc->iddos ?>" data-confirm="<?= $doc->nomdos ?>"><span class="glyphicon glyphicon-trash text-danger"></span></a></td><?php endif; ?>
                    </tr>
                <?php endforeach; ?>

            </table>
        </div>
    </div>
</div>
