<?php

if (!isset($docFiles)) {
    $docFiles = [];
}
if (!isset($dossier)) {
    $dossier = [];
}
?>
<div class="contain">
    <h4 class="text-info">Dossier <?= $dossier->nomdos ?></h4>

    <form method="post" id="form-folder" action="newFolder" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-3">
                <span><img src="../public/img/folder.jpg"></span><br>
                <input type="text" class="form-control inputF" placeholder="Nom du dossier" name="foldername" value="<?= $dossier->nomdos ?>" required=""><br>

                <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check btn-primary"></i> Enregistrer </button>
                <span>&nbsp;</span>
                <a href="newFolder" type="button" class="btn btn-default btn-sm"> Nouveau dossier </a>
            </div>

            <div style="float: left; border: 1px solid #ccc; height: 250px;"></div>

            <div class="col-md-8">
                <table class="table table-responsive">
                    <tr>
                        <td colspan="4">
                            <span class="col-md-6"><input type="text" name="descfile[]" class="form-control" placeholder="description fichier" required=""></span>
                            <span class="col-md-4"><input type="file" name="fichier[]"></span>
                            <span class="col-md-2" id="bloc-button">
                                <button type="button" class="btn btn-success btn-xs"  id="addDoc" >
                                    <i class="fa fa-plus"></i> &nbsp;Ajouter un fichier
                                </button>
                            </span><br>

                        </td>
                    </tr>                               
                </table> 
                <table class="table table-responsive"id="tableau_doc" >
                    <tr>
                        <td colspan="4">
                        </td>
                    </tr>
                </table>

            </div>        
        </div>
    </form>
    <div class="clearfix">&nbsp;</div>

    <div class="col-md-12 row notification">
        <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div><p><?php $this->flashSession->output() ?></p></div>
<?php endif; ?>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-responsive table-striped">
                <tr class="table-striped">
                    <td> </td>
                    <td><b>N&deg;</b></td>
                    <td><b>Nom fichier</b></td>
                    <td><b>file(s)</b></td>
                    <td align='center'><b>ouvrir</b></td>
                    <td align='center'><b>supprimer</b></td>
                </tr>
                <?php $i=0; foreach ($docFiles as $file): $i++ ?>
                <tr class="table-striped">
                    <td><img src="../public/img/fich.jpg" width="20" height="20"></td>
                    <td><b><?= $i ?></b></td>
                    <td><?= $file->description ?></td>
                    <td><?= $file->nomfile ?></td>
                    <td align="center"><a href="#"><span class="glyphicon glyphicon-pencil text-primary"></span></a></td>
                    <td align="center"><a href="deleteFile?id=<?= $file->idfile ?>" data-confirm="<?= $file->description ?>"><span class="glyphicon glyphicon-trash text-danger"></span></a></td>
                </tr>
                <?php endforeach; ?>
                
            </table>
        </div>
    </div>
</div>


