<?php

if (!isset($docFiles)) {
    $docFiles = [];
}
if (!isset($dossier)) {
    $dossier = [];
}
?>
<div class="contain">
    <h4 class="text-warning">Dossier <?= $dossier->nomdos ?></h4>

    <form method="post" id="form-folder" action="addFile" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-3">
                <div class="clearfix">&nbsp;</div>
                <span><i class="fa fa-folder-open-o fa-5x text-warning"></i></span><br>
                <input type="text" class="form-control inputF" placeholder="Nom du dossier" name="foldername" value="<?= $dossier->nomdos ?>" required=""><br>
                 <div class="clearfix">&nbsp;</div>
                <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check btn-primary"></i> Enregistrer </button>
                <span>&nbsp;</span>
                <a href="newFolder" type="button" class="btn btn-default btn-sm"><i class="fa fa-backward text-warning"></i> cr&eacute;er dossiers </a>
            </div>
            <input type="hidden" name="iddos" value="<?= $dossier->iddos ?>">
            <div style="float: left; border: 1px solid #ccc; height: 250px;"></div>

            <div class="col-md-8">
                <table class="table table-responsive">
                    <tr>
                        <td colspan="4">
                            <span class="col-md-6"><input type="text" name="descfile[]" class="form-control" placeholder="description fichier" required=""></span>
                            <span class="col-md-4"><input type="file" name="fichier[]"></span>
                            <span class="col-md-2" id="bloc-button">
                                <button type="button" class="btn btn-success btn-xs"  id="addDoc" >
                                    <i class="fa fa-plus"></i> &nbsp;Ajouter un fichier
                                </button>
                            </span><br>

                        </td>
                    </tr>                               
                </table> 
                <table class="table table-responsive"id="tableau_doc" >
                    <tr>
                        <td colspan="4">
                        </td>
                    </tr>
                </table>

            </div>        
        </div>
    </form>
    <div class="clearfix">&nbsp;</div>

    <div class="col-md-12 row notification">
        <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div><p><?php $this->flashSession->output() ?></p></div>
<?php endif; ?>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-responsive table-striped table-hover ui-datatable" 
                    data-global-search="false"
                    data-length-change="true"
                    data-info="true"
                    data-paging="true"
                    data-page-length="10"
                    >
                <thead class="table-responsive">
                <tr class="table-striped">
                    <th> </th>
                    <th><b>N&deg;</b></th>
                    <th data-filterable="text" data-sortable="true"><b>Nom fichier</b></th>
                    <th><b>file(s)</b></th>
                    <th align='center'><b>ouvrir</b></th>
                    <?php if($this->session->get('mod')=="1"): ?> <th align='center'><b>Modifier</b></th><?php endif; ?>
                    <?php if($this->session->get('sup')=="1"): ?> <th align='center'><b>supprimer</b></th><?php endif; ?>
                </tr>
                </thead>
                <tbody class="table-responsive">
                <?php $i=0; foreach ($docFiles as $file): $i++ ?>
                <tr class="table-striped">
                    <td><input type="checkbox" value=""></td>
                    <td><b><?= $i ?>&nbsp; <i class="fa fa-file text-warning"></i> </b></td>
                    <td><?= $file->description ?></td>
                    <td><?= $file->nomfile ?></td>
                    <td align="center"><a href="<?= $this->url->getBaseUri()."public/archives/".$file->nomfile ?>" target="_blank"><span class="glyphicon glyphicon-eye-open text-primary"></span></a></td>
                    <?php if($this->session->get('mod')=="1"): ?><td align="center"><a href="updateFile?id=<?= $file->idfile.'.'.$dossier->iddos ?>"><span class="glyphicon glyphicon-pencil text-warning"></span></a></td><?php endif; ?>
                    <?php if($this->session->get('sup')=="1"): ?><td align="center"><a href="deleteFile?id=<?= $file->idfile ?>" data-confirm="<?= $file->description ?>"><span class="glyphicon glyphicon-trash text-danger"></span></a></td><?php endif; ?>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>


